services:
  
  mysql:
    image: mysql
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: mistrain2P@
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: Mahdi
      MYSQL_PASSWORD: mahdiPassword2
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: phonebook-app
    # ports:
    #   - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
      - ./nodemon.json:/usr/src/app/nodemon.json
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql
      PMA_USER: Mahdi
      PMA_PASSWORD: mahdiPassword2
    ports:
      - "8080:80"
    depends_on:
      - mysql
    
volumes:
  mysql_data:

networks:
  my_app_network:

