services:
  mysql:
    image: mysql
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: mistrain2P@
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: Mahdi
      MYSQL_PASSWORD: mahdiPassword2
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    # networks:
    #   - phonebook_network

  # phonebook:
  #   image: node-phonebook
  #   depends_on:
  #     - mysql

  phonebook:
    build: .
    container_name: phonebook_app
    command: ["npm", "run", "start:dev", "--", "-eng", "mysql"]
    environment:
      - NODE_ENV=development
    depends_on:
      - mysql
    volumes:
      - .:/app
    # networks:
    #   - phonebook_network
    # tty: true  # Keep the container alive

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql
      PMA_USER: Mahdi
      PMA_PASSWORD: mahdiPassword2
    ports:
      - "8080:80"
    depends_on:
      - mysql
    # networks:
    #   - phonebook_network

volumes:
  mysql_data:

networks:
  phonebook_network:
    driver: bridge