services:
  mysql:
    image: mysql
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: mistrain2P@
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: Mahdi
      MYSQL_PASSWORD: mahdiPassword2
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: userpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data: